'use client';

import { createContext, useContext, useState, useEffect } from 'react';

// Language context
const LanguageContext = createContext();

// Translation data
const translations = {
  en: {
    // Settings
    settings: 'Settings',
    general: 'General',
    notifications: 'Notifications',
    appearance: 'Appearance',
    security: 'Security',
    generalPreferences: 'General Preferences',
    language: 'Language',
    languageDescription: 'Choose your preferred language',
    timezone: 'Timezone',
    timezoneDescription: 'Set your local timezone',
    autoSave: 'Auto Save',
    autoSaveDescription: 'Automatically save changes',
    notificationPreferences: 'Notification Preferences',
    pushNotifications: 'Push Notifications',
    pushNotificationsDescription: 'Receive notifications in browser',
    emailAlerts: 'Email Alerts',
    emailAlertsDescription: 'Receive email notifications',
    appearanceSettings: 'Appearance Settings',
    darkMode: 'Dark Mode',
    darkModeDescription: 'Switch to dark theme',
    themePreview: 'Theme Preview',
    lightTheme: 'Light Theme',
    darkTheme: 'Dark Theme',
    current: 'Current',
    comingSoon: 'Coming soon',
    securitySettings: 'Security Settings',
    securityNotice: 'Security Notice',
    securityNoticeDescription: 'Security settings are managed by your system administrator.',
    twoFactorAuth: 'Two-Factor Authentication',
    twoFactorAuthDescription: 'Add an extra layer of security',
    passwordChange: 'Password Change',
    passwordChangeDescription: 'Update your password',
    sessionManagement: 'Session Management',
    sessionManagementDescription: 'Manage active sessions',
    enable: 'Enable',
    change: 'Change',
    view: 'View',
    addAlert: 'This Room Code already exists. Unable to add the room. Please try again.',
    
    // Common
    save: 'Save',
    cancel: 'Cancel',
    loading: 'Loading...',
    error: 'Error',
    success: 'Success',
    
    // Navigation
    dashboard: 'Dashboard',
    profile: 'Profile',
    logout: 'Logout',
    
    // Room Details
    roomDetails: 'Room Details',
    roomCode: 'Room Code',
    totalRooms: 'Total Rooms',
    openRooms: 'Open Rooms',
    closedRooms: 'Closed Rooms',
    addStock: 'Add Room List',
    addRoom: 'Add Room',
    backToDashboard: 'Back to Dashboard',
    roomInformation: 'Room Information',
    noRoomsFound: 'No rooms found',
    filter: 'Filter',
    allRooms: 'All Rooms',
    openOnly: 'Open Only',
    closedOnly: 'Closed Only',
    cards: 'Cards',
    list: 'List',
    category: 'Category',
    price: 'Price',
    beds: 'Beds',
    guests: 'Guests',
    total: 'Total',
    vacant: 'Vacant',
    facilities: 'Facilities',
    details: 'Details',
    delete: 'Delete',
    open: 'Available',
    close: 'Unavailable',
    inuse: 'In use',
    
    // Actions
    tryAgain: 'Try Again',
    loadingRoomDetails: 'Loading room details...',
    failedToFetchRoomData: 'Failed to fetch room data. Please try again.',
    statusUpdatedSuccessfully: 'Status updated successfully!',
    failedToUpdateStatus: 'Failed to update status. Please try again.',
    areYouSureDelete: 'Are you sure you want to delete this item?',
    itemDeletedSuccessfully: 'Item deleted successfully!',
    failedToDeleteItem: 'Failed to delete item. Please try again.',
    
    // Dashboard
    dashboard: 'Dashboard',
    welcome: 'Welcome',
    totalRooms: 'Total Rooms',
    availableRooms: 'Available Rooms',
    occupiedRooms: 'Occupied Rooms',
    search: 'Search',
    searchByCode: 'Search by Code',
    searchByName: 'Search by Name',
    searchByCategory: 'Search by Category',
    hotel: 'Hotel',
    museum: 'Museum',
    reset: 'Reset',
    edit: 'Edit',
    delete: 'Delete',
    actions: 'Available Rooms',
    status: 'Status',
    setting: 'Setting',
    noDataFound: 'No data found',
    loadingData: 'Loading data...',
    errorLoadingData: 'Error loading data',
    confirmDelete: 'Confirm Delete',
    deleteConfirmation: 'Are you sure you want to delete this item?',
    deleteSuccess: 'Item deleted successfully',
    deleteError: 'Failed to delete item',
    searchResults: 'Search Results',
    noSearchResults: 'No search results found',
    
    // Login
    login: 'Login',
    email: 'Email',
    password: 'Password',
    loginButton: 'Login',
    loginLoading: 'Logging in...',
    emailRequired: 'Email is required',
    passwordRequired: 'Password is required',
    invalidCredentials: 'Email or password is incorrect. Please try again.',
    loginError: 'An error occurred while logging in.',
    apiNotFound: 'API endpoint not found, please contact administrator.',
    showPassword: 'Show password',
    hidePassword: 'Hide password',
    
    // Sidebar
    orders: 'Orders',
    totalOrders: 'Total Orders',
    confirmedOrders: 'Confirmed Orders',
    cancelledOrders: 'Cancelled Orders',
    reports: 'Reports',
    profile: 'Profile',
    settings: 'Settings',
    logout: 'Logout',
    
    // Add Room
    addNewRoom: 'Add New Room',
    roomInformation: 'Room Information',
    fillRoomDetails: 'Fill in all room details completely',
    roomCode: 'Room Code',
    roomName: 'Room Name',
    roomType: 'Room Type',
    facilities: 'Facilities',
    numberOfBeds: 'Number of Beds',
    maximumGuests: 'Maximum Guests',
    pricePerNight: 'Price per Night (JPY)',
    status: 'Status',
    additionalDetails: 'Additional Details',
    selectRoomType: 'Select Room Type',
    loadingRoomTypes: 'Loading room types...',
    needNewRoomType: 'Need a new room type?',
    createNewType: 'Create New Type',
    active: 'Active',
    inactive: 'Inactive',
    additionalRoomDetails: 'Additional room details such as view, room size, special amenities...',
    cancel: 'Cancel',
    addRoom: 'Add Room',
    adding: 'Adding...',
    roomAddedSuccessfully: 'Room added successfully!',
    failedToAddRoom: 'Failed to add room. Please try again.',
    addRoom: 'Add Room',
  },
  th: {
    // Settings
    settings: 'ตั้งค่า',
    general: 'ทั่วไป',
    notifications: 'การแจ้งเตือน',
    appearance: 'ลักษณะ',
    security: 'ความปลอดภัย',
    generalPreferences: 'การตั้งค่าทั่วไป',
    language: 'ภาษา',
    languageDescription: 'เลือกภาษาที่คุณต้องการ',
    timezone: 'เขตเวลา',
    timezoneDescription: 'ตั้งค่าเขตเวลาท้องถิ่น',
    autoSave: 'บันทึกอัตโนมัติ',
    autoSaveDescription: 'บันทึกการเปลี่ยนแปลงโดยอัตโนมัติ',
    notificationPreferences: 'การตั้งค่าการแจ้งเตือน',
    pushNotifications: 'การแจ้งเตือนแบบพุช',
    pushNotificationsDescription: 'รับการแจ้งเตือนในเบราว์เซอร์',
    emailAlerts: 'การแจ้งเตือนทางอีเมล',
    emailAlertsDescription: 'รับการแจ้งเตือนทางอีเมล',
    appearanceSettings: 'การตั้งค่าลักษณะ',
    darkMode: 'โหมดมืด',
    darkModeDescription: 'เปลี่ยนเป็นธีมมืด',
    themePreview: 'ตัวอย่างธีม',
    lightTheme: 'ธีมสว่าง',
    darkTheme: 'ธีมมืด',
    current: 'ปัจจุบัน',
    comingSoon: 'เร็วๆ นี้',
    securitySettings: 'การตั้งค่าความปลอดภัย',
    securityNotice: 'หมายเหตุความปลอดภัย',
    securityNoticeDescription: 'การตั้งค่าความปลอดภัยถูกจัดการโดยผู้ดูแลระบบ',
    twoFactorAuth: 'การยืนยันตัวตนแบบสองขั้นตอน',
    twoFactorAuthDescription: 'เพิ่มชั้นความปลอดภัยเพิ่มเติม',
    passwordChange: 'เปลี่ยนรหัสผ่าน',
    passwordChangeDescription: 'อัปเดตรหัสผ่านของคุณ',
    sessionManagement: 'การจัดการเซสชัน',
    sessionManagementDescription: 'จัดการเซสชันที่ใช้งานอยู่',
    enable: 'เปิดใช้งาน',
    change: 'เปลี่ยน',
    view: 'ดู',
    
    // Common
    save: 'บันทึก',
    cancel: 'ยกเลิก',
    loading: 'กำลังโหลด...',
    error: 'ข้อผิดพลาด',
    success: 'สำเร็จ',
    
    // Navigation
    dashboard: 'แดชบอร์ด',
    profile: 'โปรไฟล์',
    logout: 'ออกจากระบบ',
    
    // Room Details
    roomDetails: 'รายละเอียดห้อง',
    roomCode: 'รหัสห้อง',
    totalRooms: 'ห้องทั้งหมด',
    openRooms: 'ห้องที่เปิด',
    closedRooms: 'ห้องที่ปิด',
    addStock: 'เพิ่มรายการห้อง',
    addRoom: 'เพิ่มห้อง',
    backToDashboard: 'กลับไปยังแดชบอร์ด',
    roomInformation: 'ข้อมูลห้อง',
    noRoomsFound: 'ไม่พบห้อง',
    filter: 'กรอง',
    allRooms: 'ห้องทั้งหมด',
    openOnly: 'เปิดเท่านั้น',
    closedOnly: 'ปิดเท่านั้น',
    cards: 'การ์ด',
    list: 'รายการ',
    category: 'หมวดหมู่',
    price: 'ราคา',
    beds: 'เตียง',
    guests: 'แขก',
    total: 'ทั้งหมด',
    vacant: 'ว่าง',
    facilities: 'สิ่งอำนวยความสะดวก',
    details: 'รายละเอียด',
    delete: 'ลบ',
    open: 'เปิด',
    close: 'ปิด',
    
    // Actions
    tryAgain: 'ลองอีกครั้ง',
    loadingRoomDetails: 'กำลังโหลดรายละเอียดห้อง...',
    failedToFetchRoomData: 'ไม่สามารถดึงข้อมูลห้องได้ กรุณาลองอีกครั้ง',
    statusUpdatedSuccessfully: 'อัปเดตสถานะสำเร็จ!',
    failedToUpdateStatus: 'ไม่สามารถอัปเดตสถานะได้ กรุณาลองอีกครั้ง',
    areYouSureDelete: 'คุณแน่ใจหรือไม่ที่จะลบรายการนี้?',
    itemDeletedSuccessfully: 'ลบรายการสำเร็จ!',
    failedToDeleteItem: 'ไม่สามารถลบรายการได้ กรุณาลองอีกครั้ง',
    
    // Dashboard
    dashboard: 'แดชบอร์ด',
    welcome: 'ยินดีต้อนรับ',
    totalRooms: 'ห้องทั้งหมด',
    availableRooms: 'ห้องว่าง',
    occupiedRooms: 'ห้องที่ถูกใช้งาน',
    search: 'ค้นหา',
    searchByCode: 'ค้นหาตามรหัส',
    searchByName: 'ค้นหาตามชื่อ',
    searchByCategory: 'ค้นหาตามหมวดหมู่',
    hotel: 'โรงแรม',
    museum: 'พิพิธภัณฑ์',
    reset: 'รีเซ็ต',
    edit: 'แก้ไข',
    delete: 'ลบ',
    actions: 'การดำเนินการ',
    noDataFound: 'ไม่พบข้อมูล',
    loadingData: 'กำลังโหลดข้อมูล...',
    errorLoadingData: 'เกิดข้อผิดพลาดในการโหลดข้อมูล',
    confirmDelete: 'ยืนยันการลบ',
    deleteConfirmation: 'คุณแน่ใจหรือไม่ที่จะลบรายการนี้?',
    deleteSuccess: 'ลบรายการสำเร็จ',
    deleteError: 'ไม่สามารถลบรายการได้',
    searchResults: 'ผลการค้นหา',
    noSearchResults: 'ไม่พบผลการค้นหา',
    
    // Login
    login: 'เข้าสู่ระบบ',
    email: 'อีเมล',
    password: 'รหัสผ่าน',
    loginButton: 'เข้าสู่ระบบ',
    loginLoading: 'กำลังเข้าสู่ระบบ...',
    emailRequired: 'กรุณากรอกอีเมล',
    passwordRequired: 'กรุณากรอกรหัสผ่าน',
    invalidCredentials: 'อีเมลหรือรหัสผ่านไม่ถูกต้อง กรุณาลองอีกครั้ง',
    loginError: 'เกิดข้อผิดพลาดในการเข้าสู่ระบบ',
    apiNotFound: 'ไม่พบ API endpoint กรุณาติดต่อผู้ดูแลระบบ',
    showPassword: 'แสดงรหัสผ่าน',
    hidePassword: 'ซ่อนรหัสผ่าน',
    
    // Sidebar
    orders: 'คำสั่งซื้อ',
    totalOrders: 'คำสั่งซื้อทั้งหมด',
    confirmedOrders: 'คำสั่งซื้อที่ยืนยันแล้ว',
    cancelledOrders: 'คำสั่งซื้อที่ยกเลิก',
    reports: 'รายงาน',
    profile: 'โปรไฟล์',
    settings: 'ตั้งค่า',
    logout: 'ออกจากระบบ',
    
    // Add Room
    addNewRoom: 'เพิ่มห้องใหม่',
    roomInformation: 'ข้อมูลห้อง',
    fillRoomDetails: 'กรอกข้อมูลห้องให้ครบถ้วน',
    roomCode: 'รหัสห้อง',
    roomName: 'ชื่อห้อง',
    roomType: 'ประเภทห้อง',
    facilities: 'สิ่งอำนวยความสะดวก',
    numberOfBeds: 'จำนวนเตียง',
    maximumGuests: 'จำนวนแขกสูงสุด',
    pricePerNight: 'ราคาต่อคืน (JPY)',
    status: 'สถานะ',
    additionalDetails: 'รายละเอียดเพิ่มเติม',
    selectRoomType: 'เลือกประเภทห้อง',
    loadingRoomTypes: 'กำลังโหลดประเภทห้อง...',
    needNewRoomType: 'ต้องการประเภทห้องใหม่?',
    createNewType: 'สร้างประเภทใหม่',
    active: 'เปิดใช้งาน',
    inactive: 'ปิดใช้งาน',
    additionalRoomDetails: 'รายละเอียดห้องเพิ่มเติม เช่น มุมมอง ขนาดห้อง สิ่งอำนวยความสะดวกพิเศษ...',
    cancel: 'ยกเลิก',
    addRoom: 'เพิ่มห้อง',
    adding: 'กำลังเพิ่ม...',
    roomAddedSuccessfully: 'เพิ่มห้องสำเร็จ!',
    failedToAddRoom: 'ไม่สามารถเพิ่มห้องได้ กรุณาลองอีกครั้ง',
    addRoom: 'เพิ่มห้อง',
  },
  ja: {
    // Settings
    settings: '設定',
    general: '一般',
    notifications: '通知',
    appearance: '外観',
    security: 'セキュリティ',
    generalPreferences: '一般設定',
    language: '言語',
    languageDescription: 'お好みの言語を選択してください',
    timezone: 'タイムゾーン',
    timezoneDescription: 'ローカルタイムゾーンを設定',
    autoSave: '自動保存',
    autoSaveDescription: '変更を自動保存',
    notificationPreferences: '通知設定',
    pushNotifications: 'プッシュ通知',
    pushNotificationsDescription: 'ブラウザで通知を受信',
    emailAlerts: 'メールアラート',
    emailAlertsDescription: 'メール通知を受信',
    appearanceSettings: '外観設定',
    darkMode: 'ダークモード',
    darkModeDescription: 'ダークテーマに切り替え',
    themePreview: 'テーマプレビュー',
    lightTheme: 'ライトテーマ',
    darkTheme: 'ダークテーマ',
    current: '現在',
    comingSoon: '近日公開',
    securitySettings: 'セキュリティ設定',
    securityNotice: 'セキュリティ通知',
    securityNoticeDescription: 'セキュリティ設定はシステム管理者によって管理されています',
    twoFactorAuth: '二要素認証',
    twoFactorAuthDescription: 'セキュリティの追加レイヤー',
    passwordChange: 'パスワード変更',
    passwordChangeDescription: 'パスワードを更新',
    sessionManagement: 'セッション管理',
    sessionManagementDescription: 'アクティブセッションを管理',
    enable: '有効化',
    change: '変更',
    view: '表示',
    
    // Common
    save: '保存',
    cancel: 'キャンセル',
    loading: '読み込み中...',
    error: 'エラー',
    success: '成功',
    
    // Navigation
    dashboard: 'ダッシュボード',
    profile: 'プロフィール',
    logout: 'ログアウト',
    
    // Room Details
    roomDetails: '部屋詳細',
    roomCode: '部屋コード',
    totalRooms: '総部屋数',
    openRooms: '空室',
    closedRooms: '閉室',
    addStock: '在庫追加',
    backToDashboard: 'ダッシュボードに戻る',
    roomInformation: '部屋情報',
    noRoomsFound: '部屋が見つかりません',
    filter: 'フィルター',
    allRooms: 'すべての部屋',
    openOnly: '空室のみ',
    closedOnly: '閉室のみ',
    cards: 'カード',
    list: 'リスト',
    category: 'カテゴリー',
    price: '価格',
    beds: 'ベッド',
    guests: 'ゲスト',
    total: '合計',
    vacant: '空室',
    facilities: '設備',
    details: '詳細',
    delete: '削除',
    open: '開く',
    close: '閉じる',
    
    // Actions
    tryAgain: '再試行',
    loadingRoomDetails: '部屋詳細を読み込み中...',
    failedToFetchRoomData: '部屋データの取得に失敗しました。再試行してください。',
    statusUpdatedSuccessfully: 'ステータスが正常に更新されました！',
    failedToUpdateStatus: 'ステータスの更新に失敗しました。再試行してください。',
    areYouSureDelete: 'このアイテムを削除してもよろしいですか？',
    itemDeletedSuccessfully: 'アイテムが正常に削除されました！',
    failedToDeleteItem: 'アイテムの削除に失敗しました。再試行してください。',
    
    // Dashboard
    dashboard: 'ダッシュボード',
    welcome: 'ようこそ',
    totalRooms: '総部屋数',
    availableRooms: '空室',
    occupiedRooms: '使用中',
    search: '検索',
    searchByCode: 'コードで検索',
    searchByName: '名前で検索',
    searchByCategory: 'カテゴリーで検索',
    hotel: 'ホテル',
    museum: '博物館',
    reset: 'リセット',
    edit: '編集',
    delete: '削除',
    actions: 'アクション',
    noDataFound: 'データが見つかりません',
    loadingData: 'データを読み込み中...',
    errorLoadingData: 'データの読み込みエラー',
    confirmDelete: '削除の確認',
    deleteConfirmation: 'このアイテムを削除してもよろしいですか？',
    deleteSuccess: 'アイテムが正常に削除されました',
    deleteError: 'アイテムの削除に失敗しました',
    searchResults: '検索結果',
    noSearchResults: '検索結果が見つかりません',
    
    // Login
    login: 'ログイン',
    email: 'メールアドレス',
    password: 'パスワード',
    loginButton: 'ログイン',
    loginLoading: 'ログイン中...',
    emailRequired: 'メールアドレスが必要です',
    passwordRequired: 'パスワードが必要です',
    invalidCredentials: 'メールアドレスまたはパスワードが正しくありません。再試行してください。',
    loginError: 'ログイン中にエラーが発生しました。',
    apiNotFound: 'APIエンドポイントが見つかりません。管理者にお問い合わせください。',
    showPassword: 'パスワードを表示',
    hidePassword: 'パスワードを非表示',
    
    // Sidebar
    orders: '注文',
    totalOrders: '総注文数',
    confirmedOrders: '確認済み注文',
    cancelledOrders: 'キャンセル注文',
    reports: 'レポート',
    profile: 'プロフィール',
    settings: '設定',
    logout: 'ログアウト',
    
    // Add Room
    addNewRoom: '新しい部屋を追加',
    roomInformation: '部屋情報',
    fillRoomDetails: '部屋の詳細を完全に入力してください',
    roomCode: '部屋コード',
    roomName: '部屋名',
    roomType: '部屋タイプ',
    facilities: '設備',
    numberOfBeds: 'ベッド数',
    maximumGuests: '最大ゲスト数',
    pricePerNight: '一泊料金 (JPY)',
    status: 'ステータス',
    additionalDetails: '追加詳細',
    selectRoomType: '部屋タイプを選択',
    loadingRoomTypes: '部屋タイプを読み込み中...',
    needNewRoomType: '新しい部屋タイプが必要ですか？',
    createNewType: '新しいタイプを作成',
    active: 'アクティブ',
    inactive: '非アクティブ',
    additionalRoomDetails: '眺め、部屋サイズ、特別な設備などの追加部屋詳細...',
    cancel: 'キャンセル',
    addRoom: '部屋を追加',
    adding: '追加中...',
    roomAddedSuccessfully: '部屋が正常に追加されました！',
    failedToAddRoom: '部屋の追加に失敗しました。再試行してください。',
    addRoom: '部屋を追加',
  }
};

export function LanguageProvider({ children }) {
  const [currentLanguage, setCurrentLanguage] = useState('en');

  // Load language from localStorage on mount
  useEffect(() => {
    const savedLanguage = localStorage.getItem('language');
    if (savedLanguage && translations[savedLanguage]) {
      setCurrentLanguage(savedLanguage);
    }
  }, []);

  // Save language to localStorage when it changes
  const changeLanguage = (language) => {
    if (translations[language]) {
      setCurrentLanguage(language);
      localStorage.setItem('language', language);
    }
  };

  // Get translation function
  const t = (key) => {
    return translations[currentLanguage]?.[key] || translations.en[key] || key;
  };

  const value = {
    currentLanguage,
    changeLanguage,
    t,
    translations
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
} 